Issue 1096: use Default-Branch
puppetlabs/r10k pull request #1097
Opened 2020-10-28 03:59 UTC by cocker-cc

Use Default-Branch defined by the Upstream-Repo, if no Reference is given.
This Fix is only successful, if the cached Repos are deleted beforehead.

Note: Nowadays the Default-Branch is not always 'master'.  Many Repos
use 'main' f.e.

Please add all notable changes to the "Unreleased" section of the CHANGELOG in the format:
```
- [Issue 1096](https://github.com/puppetlabs/r10k/issues/1096): use Default-Branch, if no Ref is given
```

2020-10-28 10:28 UTC, cocker-cc commented
I guess, someone with more Insight has to find out, why some Tests break.

2020-11-08 20:46 UTC, dhollinger commented
To get the tests to pass, you need to set `"master"` on [line 69](https://github.com/puppetlabs/r10k/pull/1097/files#diff-1fa6cc3efd8f8c5d45d1d4638d1201a3b8e04890e0445ca08421222d29b62196R69) to `"HEAD"`

2020-11-08 20:47 UTC, dhollinger requested changes
To get the tests to pass, you need to set `"master"` on [line 69](https://github.com/puppetlabs/r10k/pull/1097/files#diff-1fa6cc3efd8f8c5d45d1d4638d1201a3b8e04890e0445ca08421222d29b62196R69) to `"HEAD"`

2020-11-23 20:41 UTC, jpogran commented
@puppetlabs/puppetserver-maintainers This changeset is needed to support Puppet supported modules that move toward using `main` as the default branch.

2020-11-23 21:16 UTC, dhollinger submitted a review, later dismissed
LGTM

2020-11-23 22:23 UTC, mwaggett commented
This looks good! I'm just gonna add a changelog entry.

@jpogran Will you need this released sooner rather than later?

2020-11-23 22:54 UTC, jpogran commented
Yeah, but I think the release can wait until after the holidays this week. It was more important to me to get it looked at before people left so any issues could be addressed asynchronous you

2020-11-23 23:00 UTC, mwaggett approved these changes

2020-11-23 23:01 UTC, dhollinger approved these changes

2020-11-23 23:04 UTC, mwaggett commented
okay @jpogran thanks! We might need a reminder after the holiday, but we'll try to get this out soon.

2020-11-23 23:12 UTC, merged

2021-08-10 13:11 UTC, cdenneen commented
@jpogran @dhollinger 

r10k 3.10.0
puppetlabs/stdlib

`Could not resolve desired ref 'master' and no default provided`

2021-08-10 21:48 UTC, mwaggett commented
@cdenneen Looking at the [original issue](https://github.com/puppetlabs/r10k/issues/1096), it mentions that you will need to delete the r10k cache for the repo in question in order for this to behave appropriately. If you're still having trouble, could you please open a new issue detailing your problem and steps to reproduce? Thanks!

2021-10-22 12:58 UTC, bpottier commented
Does this address the same issue with Code Manager? We are not able to pull modules that have a default branch of "main". 

puppet-code version 3.2.0

2021-10-22 16:54 UTC, mwaggett commented
@bpottier unfortunately we ended up having to revert this change - see https://github.com/puppetlabs/r10k/pull/1111 for more info. But generally, Code Manager uses r10k under the hood, so any bugs/features in r10k will also affect Code Manager.