[puppetlabs/r10k] (GH-645) Fix undefined method if r10.yaml empty
puppetlabs/r10k pull request #646
Opened 2016-09-02 08:52 UTC by GeoffWilliams

Protect the call to `symbolize_keys!` by raising ConfigError with helpful message if no YAML was loaded

2016-12-19 18:32 UTC, scotje requested changes
Looks good, just a couple tiny code style changes requested. Thanks!

2016-12-19 18:32 UTC, scotje commented on lib/r10k/settings/loader.rb
> +        if ! contents
Can you remove the space between `!` and `contents`?

2016-12-19 18:32 UTC, scotje commented on lib/r10k/settings/loader.rb
> +          raise ConfigError, _("File exists at #{path} but doesn't contain any YAML") % {path:path}
Add a space between `path:` and `path` in the map at the end of the line.

2017-03-11 11:50 UTC, GeoffWilliams commented
@scotje Sorry for the delay - I just saw your message.  Requested changes committed, thanks

2017-03-13 21:52 UTC, scotje approved these changes

2017-03-13 21:53 UTC, merged