(RK-290) Add deprecation warning about duplicate module names
puppetlabs/r10k pull request #724
Opened 2017-04-25 21:48 UTC by ajroetker

This commit backports the duplicate module names error message code to
2.5.x as a deprecation warning.

2017-04-26 18:47 UTC, andersonmills requested changes

2017-04-26 18:47 UTC, andersonmills commented on lib/r10k/puppetfile.rb
> +  def validate_no_duplicate_names(modules)
I think you forgot to actually call this on load!

2017-04-26 18:50 UTC, ajroetker commented on lib/r10k/puppetfile.rb
> +  def validate_no_duplicate_names(modules)
Fixed up!

2017-04-26 19:01 UTC, andersonmills approved these changes
```
roquefort:~/puppet/src/r10k (PR724)
$ be r10k puppetfile check
WARN     -> Puppetfiles should contain duplicate module names and will result in an error in r10k v3.x. Please remove the remove the duplicates of the following modules:
motd
Syntax OK
```

2017-04-26 19:05 UTC, andersonmills requested changes

2017-04-26 19:05 UTC, andersonmills commented on lib/r10k/puppetfile.rb
> +      logger.warn _("Puppetfiles should contain duplicate module names and will result in an error in r10k v3.x. Please remove the remove the duplicates of the following modules:\n%{dupes}" % {dupes:
I now think these \n's should be spaces, and this should all be on one line in the log.

2017-04-26 22:30 UTC, haus commented on lib/r10k/puppetfile.rb
> +      logger.warn _("Puppetfiles should contain duplicate module names and will result in an error in r10k v3.x. Please remove the remove the duplicates of the following modules:\n%{dupes}" % {dupes:
"Please remove the remove the " => "Remove the"

2017-04-26 22:31 UTC, haus commented on lib/r10k/puppetfile.rb
> +      logger.warn _("Puppetfiles should contain duplicate module names and will result in an error in r10k v3.x. Please remove the remove the duplicates of the following modules:\n%{dupes}" % {dupes:
the log message itself should be split into two `_()` calls though.

2017-04-26 22:33 UTC, haus commented on lib/r10k/puppetfile.rb
> +      logger.warn _("Please remove the remove the duplicates of the following modules: %{dupes}" % {dupes: dupes.join(" ")})
"Please remove the remove the " => "Remove the "

2017-04-26 22:40 UTC, ajroetker commented
@andersonmills should be fixed up

2017-04-26 22:40 UTC, ajroetker commented
corresponding change to the master branch @andersonmills https://github.com/puppetlabs/r10k/pull/727

2017-04-26 22:55 UTC, haus approved these changes
LGTM

2017-04-28 16:49 UTC, andersonmills approved these changes
Well, I *thought* it was good.

2017-04-28 16:52 UTC, andersonmills requested changes

2017-04-28 16:52 UTC, andersonmills commented on lib/r10k/puppetfile.rb
> +      logger.warn _('Puppetfiles should contain duplicate module names and will result in an error in r10k v3.x.')
Hah! "Puppetfiles should contain duplicate module names"

You forgot a "not"

2017-05-01 17:55 UTC, andersonmills approved these changes

2017-05-01 17:55 UTC, merged