add filter_command directive (git only)
puppetlabs/r10k pull request #823
Opened 2018-07-07 17:51 UTC by mhumpula

please consider for merging.

## motivation
In my current puppet setup, the git repository is hosted on the shared git manager with wide user base. Though the repository has correct permissions configured I would like to be able to add some extra checks. Specifically stop the deployment of the code, that is not signed with proper gpg key by using built-in git gpg funkcionality.

The check script is easy, but I need to intercept the r10k deployment between fetching the latest repository state to *cache* and the actual deployment to puppet environments. So I came up with the branch filtering hooks, which IMHO can be used by larger user base for filtering branches and environments based on their requirements.

## implementation

I've tried to model this in the same fashion as `ignore_branch_prefixes`. I've only done git implementation, because I know very little about the svn.

2020-06-30 20:38 UTC, anarcat commented
any reason why this has not been merged yet? interest?

does this work with forge modules?

2020-07-01 05:21 UTC, mhumpula commented
@anarcat I'm using this for two years now with simple script check https://gist.github.com/mhumpula/10b7a333d2a9a470f5e0e44beb5c91f0 and it works ok for my requirements. The checkout of puppet modules is done in different part of the code I believe, so it's not affected by this change.

2020-07-02 12:55 UTC, dhollinger requested changes
Just one little change in the documentation for the change. Otherwise looks good.

2020-07-02 12:55 UTC, dhollinger commented on doc/dynamic-environments/configuration.mkd
> +* R10K_BRANCH – brach which is beeing filtered
Typo here. I think you meant `branch` and not `brach`

2020-07-02 20:03 UTC, binford2k commented on doc/dynamic-environments/configuration.mkd
> +* R10K_BRANCH – brach which is beeing filtered
```suggestion
* R10K_BRANCH – branch which is being filtered
```

2020-07-02 20:03 UTC, binford2k commented on doc/dynamic-environments/configuration.mkd
> +This can be used for example for filtering out the branches with invalid gpg signature of their latests commit
```suggestion
This can be used for example for filtering out the branches with invalid gpg signature of their latest commit
```

2020-07-02 20:06 UTC, binford2k requested changes
I like it. Small typo fixes.

2020-07-21 21:22 UTC, mwaggett commented
hey @mhumpula would you mind adding a changelog entry to the 'Unreleased' section describing this change?

also @dhollinger @binford2k would love if y'all could take another look at this.

2020-07-21 21:30 UTC, binford2k commented
@mhumpula Can you also add some docs to clarify that this only works when using the git source? We'll file a ticket for the missing svn counterpart when it's merged. Otherwise, 👍

2020-07-22 06:56 UTC, mhumpula commented
@binford2k note about git added, @mwaggett added entry to changelog, but I'm not sure if it is in format you like.

2020-07-22 15:18 UTC, mwaggett commented
hey @mhumpula! Would you mind rebasing against the master branch? There have been many updates to the changelog since this PR was first opened. 😅  And then, usually, we add the PR as a link at the end of the note if there wasn't a ticket the work was based on, for example: https://github.com/puppetlabs/r10k/blob/master/CHANGELOG.mkd#350

Let us know if you need help with any of that! And thanks again for your contribution!

2020-07-22 16:18 UTC, binford2k commented
I went ahead and resolved the conflicts for you. One final review from @dhollinger and we'll get this merged! Thanks so much for the contribution @mhumpula 🎉

2020-07-22 16:28 UTC, dhollinger approved these changes

2020-07-22 16:29 UTC, binford2k approved these changes

2020-07-22 16:29 UTC, merged