POC hack to parse Puppetfile directly W/O eval
puppetlabs/r10k pull request #885
Opened 2018-12-26 23:48 UTC by binford2k

Ruby 2.6 instroduced the RubyVM::AbstractSyntaxTree, which will parse
arbitrary Ruby code into an AST. This means that instead of eval'ing
code, we can just parse it and take action on the three methods we care
about. In other words, the Puppetfile will no longer be arbitrary and
unchecked Ruby code.

See https://docs.ruby-lang.org/en/trunk/RubyVM/AbstractSyntaxTree.html
for more information.

Note: This implementation is *experimental* and will almost certainly
change. This should not be merged until upstream commits to a stable
API. But it's worth exploring and validating that we can indeed have
non-executable Puppetfiles.

2018-12-27 03:24 UTC, dhollinger reviewed
:+1:

2019-03-27 03:29 UTC, dhollinger approved these changes

2019-03-27 03:30 UTC, dhollinger requested changes
Needs rebase

2019-05-07 21:45 UTC, mdwheele commented
In our environment, we have multiple tenants separated into separate control repositories that all depend on shared modules (roles/profiles) we maintain as a community. This means that when we decide to update underlying component modules, we have to communicate those changes to individual tenants and it creates a release bottleneck.

One "hack" that we've been using in the last year was to have our r10k node write the "shared upstream `Puppetfile`" to disk and then in tenant `Puppetfile`, they do the following:

```
# "Include" shared Puppetfile
self.instance_eval(File.read('<%= @_shared_puppetfile_path %>'))

# 
# Tenant-specific dependencies
#
mod 'camptocamp-kmod', '2.3.0'
mod 'crayfishx-firewalld', '3.4.0'
```

This works out pretty well, but might be somewhat impacted by this line of development. Is there an alternative solution to this problem you would suggest? If not, is this feature something that could be gated as configuration?

2019-05-08 14:47 UTC, jadestorm commented
FWIW, I would love to see a formally supported "include" in Puppetfile parsing.

2019-05-10 18:15 UTC, mdwheele commented
I have implemented an include syntax for `Puppetfile` in #927 that also includes the `RubyVM`-based AST parser implementation in e744c0c

2019-11-28 04:20 UTC, glennsarti commented
Could also use Ripper to do the AST generation so as to lift the Ruby 2.6 restriction.

2021-03-17 18:53 UTC, binford2k commented
Ruby 2.6 is no longer an onerous requirement since 2.5 goes EOL on 2021-03-31. I would like to make a decision on this. I believe that executable Puppetfiles are dangerous. We can gate this behind a config option and make it default in 4.x.

Can someone put some 👀 on this?

2021-03-17 22:57 UTC, mwaggett commented
The [docs](https://ruby-doc.org/core-2.7.0/RubyVM/AbstractSyntaxTree.html) say that the `RubyVM::AbstractSyntaxTree` class is MRI-specific. Is that going to work when we use r10k in code-manager, since we use Jruby? /cc @puppetlabs/puppetserver-maintainers 

I agree that just calling `instance_eval` on the Puppetfile seems dangerous, but I'm hesitant about this implementation. They still say that the API is not stable and this doesn't seem very straightforward to maintain. They suggest using [parser](https://rubygems.org/gems/parser) or [Ripper](https://ruby-doc.org/core-2.7.0/Ripper.html) instead.

2021-03-17 23:18 UTC, binford2k commented
@mwaggett that's a really good point. I _think_ that CM just fork/execs r10k in its own process, but not entirely sure.

Regardless, you make a good point that parser or ripper would be better options. I unfortunately don't have time to refactor that, but I'll open a ticket to do so and reference this PR. Thanks!

2021-03-17 23:18 UTC, closed without merging