(CDPE-1813) Add module deploy info to .r10k-deploy.json file
puppetlabs/r10k pull request #955
Opened 2019-07-15 16:03 UTC by chrisleicester

With this change, module information will be added to the output file '.r10k-deploy.json' for external consumption (including the module name, version, and git sha associated with the commit used if pulling the module from a git repository

2019-07-16 17:52 UTC, binford2k requested changes
Can you add some tests for this?

2019-07-17 22:35 UTC, chrisleicester commented
@binford2k due to the way the existing r10k unit tests are written, we never _actually_ create the .r10k-deploy.json file during testing. Therefore, there is currently no way to validate if the file is being written correctly (this fact existed prior to me modifying the code). That being said, I have added integration testing to the [corresponding code-manager code changes](https://github.com/puppetlabs/code-manager/pull/418/files#diff-64617a27cc613499d1a1c3cf5619a098R215) that does a full deploy, then validates the contents of the `.r10k-deploy.json` file created by r10k.

Given that r10k can (and is) used independently of code-manager, this is not an ideal solution, but it does verify that the r10k functionality works E2E.

If this still isn't satisfactory, we can always expose the `write_environment_info` method as a public method, and unit test it that way. Currently its private. 

If you have any other suggestions on how to validate this code, please let me know!

2019-07-19 23:43 UTC, chrisleicester commented
@binford2k tests added. Please review when you have a chance.

2019-07-19 23:54 UTC, binford2k approved these changes

2019-07-23 18:36 UTC, Magisus approved these changes
Seems straightforward and useful.

2019-07-23 18:36 UTC, Magisus commented
I'll merge this when I'm done with tagging shenanigans in the pe-r10k packaging project.

2019-07-23 22:24 UTC, merged